{
  interview_report: 'Siddhi Varshney',
  candidate_information: 'Siddhi Varshney | siddhi.varshney@gmail.com | +91-9876543210 | Bengaluru, India',
  resume_summary: 'Final-year B.Tech student in Artificial Intelligence with hands-on experience in full-stack development and machine learning. Strong in backend systems using Golang and API development.',
  skills: 'Languages: C++, Python, JavaScript, Golang; Frontend: React.js, HTML, CSS; Backend: Node.js, Express, REST APIs; Database: MongoDB, MySQL; Tools: Git, Docker, Postman',
  experience: 'Full Stack Developer Intern at Instavision Inc. - Built REST APIs using Node.js and Express, developed frontend using React.js, worked with MongoDB for data storage.',
  projects: '1. AI-Based Question Generation System: Built using T5 Transformer model, generates subjective questions from context, developed interface using Gradio. 2. Suspicious Activity Detection: Used ResNet50 + BiLSTM with attention, worked on UCF-Crime dataset, implemented feature extraction and classification pipeline.',
  education: 'B.Tech in Artificial Intelligence (2021 – 2025)',
  achievements: 'IndiaAI Fellowship Award recipient',  strengths: 'Strong foundation in AI/ML with practical experience in transformer models (T5) and deep learning architectures (ResNet50 + BiLSTM). Demonstrates full-stack development capabilities with proficiency in Golang, Node.js, Express, React.js, and databases like MongoDB/MySQL. Projects showcase ability to apply theoretical knowledge to real-world problems. Received the prestigious IndiaAI Fellowship, indicating high potential.',
  weaknesses: 'As a final-year student, professional experience is limited to one internship. While skills are broad, depth in specific frameworks or complex system design might require further development and practical exposure. (Based purely on resume; actual interview might reveal more specific areas for growth).',
  overall_feedback: 'Siddhi Varshney presents as a highly promising candidate with a robust technical background in Artificial Intelligence and Full Stack Development. Their projects demonstrate a strong understanding of modern AI/ML techniques and practical application. The full-stack experience, particularly with Golang and Node.js for backend, combined with React.js for frontend, makes them a versatile asset. The IndiaAI Fellowship is a significant achievement, highlighting their academic excellence and potential. The candidate appears well-prepared for an entry-level to mid-level role where their diverse skill set can be leveraged and further developed.',
  recommendation: 'Strongly recommended for the next round of interviews. Further assessment should focus on problem-solving skills, depth of understanding in specific technologies, and ability to articulate project challenges and contributions.'
}